### ISSUE TITLE
can't find -e git+https://github.com/LAION-AI/CLAP.git@6b1b4b5b4b87f4e19d3836d2ae7d7272e1c69410#egg=laion_clap

### ISSUE THREAD

**Issue by fundwotsai2001** [zelaki/DreamSound#2]
while using pip install -r requirements, it can't find -e git+https://github.com/LAIONAI/CLAP.git@6b1b4b5b4b87f4e19d3836d2ae7d7272e1c69410#egg=laion_clap, and i click into the link and it says not found.

**Comment by manosplitsis** [comment]
Hello, clicking the link shouldn't work. Did you copy the line from requirements.txt? There should be a dash in LAION-AI: -e git+https://github.com/LAION-AI/CLAP.git@6b1b4b5b4b87f4e19d3836d2ae7d7272e1c69410#egg=laion_clap, like in the requirements.txt file. Can you try running it again and posting the console output if it doesn't work?

**Comment by fundwotsai2001** [comment]
Oh, it's fine now I don't know why. But now it is saying header file too large, but i am not sure what should be "header file". Thank you.
![image](https://github.com/zelaki/DreamSound/assets/64879498/dad7114e-471d-46f0-a489-e9d5314419e3)

![image](https://github.com/zelaki/DreamSound/assets/64879498/b3488806-e008-4190-92c3-75d557f9334c)

**Comment by zelaki** [comment]
Hello, this may be caused by using the [wrong model file](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8123). Please use the right [model name of path ](https://huggingface.co/cvssp/audioldm-m-full) for audioldm

**Comment by fundwotsai2001** [comment]
Thanks, I've solved the problem. I didn't know that i should use git lfs install before cloning models on hugging face.
